database:
  driver: postgres #postgres atau mysql
  instance_connection_name: "<PROJECT_ID>:<REGION>:<INSTANCE_NAME>"
  user: "cloud-sql-user@lv-playground-appdev.iam"
  name: "<DATABASE_NAME>"
  private: ""
